language: java
node_js:
  - "lts/*"
before_install:
  - nvm install lts/*
  - node --version
  - npm --version
  - nvm --version
  - npm i
cache:
  directories:
    - .autoconf
    - $HOME/.m2
install: true
script: mvn clean install -q -DskipTests=true
